### ISSUE TITLE
Adding of new artifacts fails because of missing maven-metadata.xml

### ISSUE THREAD

**Issue by riccardocossu** [synergian/wagon-git#25]
This was introduced by recent changes for 0.2.4, since 0.2.3 worked fine in this use case (I guess that's why file.exists() was there in the first place...).

Everything works fine with directories which are already on the git repo, but fails when a new one is created (for example you create a new library with a different artifact  Id).
That's because the wagon somehow assumes that a maven-metadata.xml should be on the repo, which is not the case since this is the first time you do a deploy.

The workaround is to usually use 0.2.4 and rollback to 0.2.3 when you need to add a new artifact or a new version number for an existing artifact.

**Comment by pwheel** [comment]
Hi @mschonaker I've tested uploading new artifacts with 0.2.5-SNAPSHOT and it works fine for me :-)

**Comment by pwheel** [comment]
Hi @mschonaker do you plan on releasing 0.2.5? It seems good, I'm using the SNAPSHOT version.

**Comment by mschonaker** [comment]
Ok. Give a moment.

**Comment by mschonaker** [comment]
Ok. It's done. I had to upgrade some dependencies to get it working under Maven 3.2.2. Let me know if it doesn't work for you.
