### ISSUE TITLE
Wagon-git releases URL returning error 400

### ISSUE THREAD

**Issue by nobre84** [synergian/wagon-git#39]
Hi! I'm trying to use wagon-git for private bitbucket maven repo for use with gradle following some of the guides posted on README.
However, `https://raw.github.com/synergian/wagon-git/releases` is issuing errors, is that the right location for using the plugin ? Or am I missing something and that should be user-url ?

Thanks!

**Comment by mschonaker** [comment]
That's the URL of a directory, that's could be the cause. Now, if you check https://raw.github.com/synergian/wagon-git/releases/ar/com/synergian/wagon-git/maven-metadata.xml (same base URL, path to a file), you should be able to see the raw XML for Maven metadata.

As you get redirected to https://raw.githubusercontent.com/synergian/wagon-git/releases/ar/com/synergian/wagon-git/maven-metadata.xml, maybe its a good idea to use https://raw.githubusercontent.com/synergian/wagon-git/releases/ as the base URL (the github.com domain was from an older version of GitHub).

Determining the base URL of the repo is not hard. Just navigate to the GitHub page where the source is and then hit the "Raw" button in any of the files. For instance, here: https://github.com/synergian/wagon-git/tree/releases/ar/com/synergian/wagon-git 

Regards.
