### ISSUE TITLE
Not compatible with Android plugin 3.0

### ISSUE THREAD

**Issue by AdrianRobinsonNBA** [synergian/wagon-git#48]
I upgraded to Android plugin 3.0 and Gradle 4.1 but when using the same gradle tasks (with the necessary changes compile -> implementation etc) the uploadArchives tasks can no longer determine the outputs. Is this because of the new variant aware behavior of the plugin ? I basically used the same file made the changes for 3.0 and I get the error "Task declared no outputs". When I use the source file and the javadoc artifacts those are uploaded just the actual aar cannot be found. Can you help with this ?

**Comment by pfaffenrodt** [comment]
Maybe this Issue is obsolete . Everything works with current build tools "3.0.1"
